"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 27;
let altura = 1.75;
const nacionalidade = 'Brasileira';
const colegas = ['lucas', 'fernanda'];
const tecnologias = ['HTML', 'CSS', 'JS'];
const notas = [7, 9, 5, 8];
const lista = ['Gian', true, 32];
let idadeDaAna = 25;
idadeDaAna = '25 Anos';
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
dadosDaApi = 'string';
